#!/bin/bash
# ==========================================
# QUICK REFERENCE - Comandos Rápidos
# ==========================================

echo "📚 DESARROLLO LOCAL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Levantar todo con Docker Compose:"
echo "  docker-compose up -d"
echo ""
echo "Ver logs:"
echo "  docker-compose logs -f api"
echo ""
echo "Detener:"
echo "  docker-compose down"
echo ""

echo "🔨 BUILD PRODUCCIÓN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Build imagen local:"
echo "  docker build -f Dockerfile.prod -t oroverde-api:latest ."
echo ""
echo "Test imagen localmente:"
echo "  docker run -p 3000:3000 --env-file .env.production.azure oroverde-api:latest"
echo ""
echo "Tamaño imagen:"
echo "  docker image ls oroverde-api:latest"
echo ""

echo "📤 PUSH A AZURE CONTAINER REGISTRY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Método 1 - Script:"
echo "  chmod +x deploy-to-acr.sh"
echo "  ./deploy-to-acr.sh oroverde oroverde-api v1.0.0"
echo ""
echo "Método 2 - Manual:"
echo "  az acr login --name oroverde"
echo "  docker tag oroverde-api:latest oroverde.azurecr.io/oroverde-api:v1.0.0"
echo "  docker push oroverde.azurecr.io/oroverde-api:v1.0.0"
echo ""

echo "🚀 DEPLOYMENT EN AZURE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Actualizar App Service con nueva imagen:"
echo "  az webapp config container set \\"
echo "    --name oroverde-api \\"
echo "    --resource-group tu-rg \\"
echo "    --docker-custom-image-name oroverde.azurecr.io/oroverde-api:v1.0.0 \\"
echo "    --docker-registry-server-url https://oroverde.azurecr.io \\"
echo "    --docker-registry-server-user <USERNAME> \\"
echo "    --docker-registry-server-password <PASSWORD>"
echo ""
echo "Ver logs desplegados:"
echo "  az webapp log tail --name oroverde-api --resource-group tu-rg"
echo ""

echo "🔍 DEBUGGING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Verificar conexión PostgreSQL:"
echo "  psql -h psql-oroverde-prod.postgres.database.azure.com \\"
echo "       -U oroverde@psql-oroverde-prod \\"
echo "       -d control_plane"
echo ""
echo "Verificar conexión Redis:"
echo "  redis-cli -h redis-oroverde-prod.northeurope.redis.azure.net \\"
echo "            -p 10000 \\"
echo "            -a <PASSWORD> ping"
echo ""
echo "Health check API:"
echo "  curl http://localhost:3000/api/health"
echo ""
echo "Generar secreto seguro:"
echo "  node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\""
echo ""

echo "📊 MONITOREO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Ver métricas App Service:"
echo "  az monitor metrics list-definitions --resource /subscriptions/<SUB>/resourceGroups/tu-rg/providers/Microsoft.Web/sites/oroverde-api"
echo ""
echo "Ver application insights:"
echo "  az monitor app-insights component show --app oroverde-app-insights --resource-group tu-rg"
echo ""

echo "🔄 ROLLBACK"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Cambiar a versión anterior:"
echo "  az webapp config container set \\"
echo "    --name oroverde-api \\"
echo "    --docker-custom-image-name oroverde.azurecr.io/oroverde-api:v1.0.0"
echo ""
echo "Listar últimas imágenes en ACR:"
echo "  az acr repository show-tags --repository oroverde-api --name oroverde"
echo ""

echo "📋 TESTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run tests:"
echo "  npm run test"
echo ""
echo "Run e2e tests:"
echo "  npm run test:e2e"
echo ""
echo "Coverage report:"
echo "  npm run test:cov"
echo ""

echo "🔐 KEY VAULT (SECRETOS)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Crear secret en Key Vault:"
echo "  az keyvault secret set --vault-name oroverde-kv \\"
echo "    --name DB-PASS \\"
echo "    --value \"tu-password-aqui\""
echo ""
echo "Leer secret:"
echo "  az keyvault secret show --vault-name oroverde-kv --name DB-PASS"
echo ""
echo "Dar permisos App Service a Key Vault:"
echo "  az keyvault set-policy --name oroverde-kv \\"
echo "    --object-id <app-identity-id> \\"
echo "    --secret-permissions get list"
echo ""

echo ""
echo "✅ MÁS INFORMACIÓN EN: DOCKER-GUIDE.md y PRODUCTION-CHECKLIST.md"
