/**
 * ALL_COUNTRIES_SEED
 *
 * Lista completa de ~250 países/territorios ISO 3166-1 alpha-2.
 * Incluye: código ISO, nombre, zona horaria IANA principal, código telefónico y región.
 *
 * Fuente: ISO 3166-1, IANA Time Zone Database
 * Uso: POST /api/admin/countries/seed
 */

export interface CountrySeed {
  code: string;
  name: string;
  timezone: string;
  phone_code: string;
  region: string;
}

export const ALL_COUNTRIES_SEED: CountrySeed[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // AMERICAS
  // ═══════════════════════════════════════════════════════════════════════
  { code: 'AG', name: 'Antigua and Barbuda',     timezone: 'America/Antigua',        phone_code: '+1-268', region: 'Americas' },
  { code: 'AR', name: 'Argentina',               timezone: 'America/Argentina/Buenos_Aires', phone_code: '+54', region: 'Americas' },
  { code: 'BS', name: 'Bahamas',                 timezone: 'America/Nassau',         phone_code: '+1-242', region: 'Americas' },
  { code: 'BB', name: 'Barbados',                timezone: 'America/Barbados',       phone_code: '+1-246', region: 'Americas' },
  { code: 'BZ', name: 'Belize',                  timezone: 'America/Belize',         phone_code: '+501',   region: 'Americas' },
  { code: 'BO', name: 'Bolivia',                 timezone: 'America/La_Paz',         phone_code: '+591',   region: 'Americas' },
  { code: 'BR', name: 'Brasil',                  timezone: 'America/Sao_Paulo',      phone_code: '+55',    region: 'Americas' },
  { code: 'CA', name: 'Canada',                  timezone: 'America/Toronto',        phone_code: '+1',     region: 'Americas' },
  { code: 'CL', name: 'Chile',                   timezone: 'America/Santiago',       phone_code: '+56',    region: 'Americas' },
  { code: 'CO', name: 'Colombia',                timezone: 'America/Bogota',         phone_code: '+57',    region: 'Americas' },
  { code: 'CR', name: 'Costa Rica',              timezone: 'America/Costa_Rica',     phone_code: '+506',   region: 'Americas' },
  { code: 'CU', name: 'Cuba',                    timezone: 'America/Havana',         phone_code: '+53',    region: 'Americas' },
  { code: 'DM', name: 'Dominica',                timezone: 'America/Dominica',       phone_code: '+1-767', region: 'Americas' },
  { code: 'DO', name: 'República Dominicana',    timezone: 'America/Santo_Domingo',  phone_code: '+1-809', region: 'Americas' },
  { code: 'EC', name: 'Ecuador',                 timezone: 'America/Guayaquil',      phone_code: '+593',   region: 'Americas' },
  { code: 'SV', name: 'El Salvador',             timezone: 'America/El_Salvador',    phone_code: '+503',   region: 'Americas' },
  { code: 'GD', name: 'Grenada',                 timezone: 'America/Grenada',        phone_code: '+1-473', region: 'Americas' },
  { code: 'GT', name: 'Guatemala',               timezone: 'America/Guatemala',      phone_code: '+502',   region: 'Americas' },
  { code: 'GY', name: 'Guyana',                  timezone: 'America/Guyana',         phone_code: '+592',   region: 'Americas' },
  { code: 'HT', name: 'Haiti',                   timezone: 'America/Port-au-Prince', phone_code: '+509',   region: 'Americas' },
  { code: 'HN', name: 'Honduras',                timezone: 'America/Tegucigalpa',    phone_code: '+504',   region: 'Americas' },
  { code: 'JM', name: 'Jamaica',                 timezone: 'America/Jamaica',        phone_code: '+1-876', region: 'Americas' },
  { code: 'MX', name: 'México',                  timezone: 'America/Mexico_City',    phone_code: '+52',    region: 'Americas' },
  { code: 'NI', name: 'Nicaragua',               timezone: 'America/Managua',        phone_code: '+505',   region: 'Americas' },
  { code: 'PA', name: 'Panamá',                  timezone: 'America/Panama',         phone_code: '+507',   region: 'Americas' },
  { code: 'PY', name: 'Paraguay',                timezone: 'America/Asuncion',       phone_code: '+595',   region: 'Americas' },
  { code: 'PE', name: 'Perú',                    timezone: 'America/Lima',           phone_code: '+51',    region: 'Americas' },
  { code: 'PR', name: 'Puerto Rico',             timezone: 'America/Puerto_Rico',    phone_code: '+1-787', region: 'Americas' },
  { code: 'KN', name: 'Saint Kitts and Nevis',   timezone: 'America/St_Kitts',       phone_code: '+1-869', region: 'Americas' },
  { code: 'LC', name: 'Saint Lucia',             timezone: 'America/St_Lucia',       phone_code: '+1-758', region: 'Americas' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', timezone: 'America/St_Vincent', phone_code: '+1-784', region: 'Americas' },
  { code: 'SR', name: 'Suriname',                timezone: 'America/Paramaribo',     phone_code: '+597',   region: 'Americas' },
  { code: 'TT', name: 'Trinidad and Tobago',     timezone: 'America/Port_of_Spain',  phone_code: '+1-868', region: 'Americas' },
  { code: 'US', name: 'United States',           timezone: 'America/New_York',       phone_code: '+1',     region: 'Americas' },
  { code: 'UY', name: 'Uruguay',                 timezone: 'America/Montevideo',     phone_code: '+598',   region: 'Americas' },
  { code: 'VE', name: 'Venezuela',               timezone: 'America/Caracas',        phone_code: '+58',    region: 'Americas' },

  // ═══════════════════════════════════════════════════════════════════════
  // EUROPE
  // ═══════════════════════════════════════════════════════════════════════
  { code: 'AL', name: 'Albania',                 timezone: 'Europe/Tirane',          phone_code: '+355',   region: 'Europe' },
  { code: 'AD', name: 'Andorra',                 timezone: 'Europe/Andorra',         phone_code: '+376',   region: 'Europe' },
  { code: 'AT', name: 'Austria',                 timezone: 'Europe/Vienna',          phone_code: '+43',    region: 'Europe' },
  { code: 'BY', name: 'Belarus',                 timezone: 'Europe/Minsk',           phone_code: '+375',   region: 'Europe' },
  { code: 'BE', name: 'Belgium',                 timezone: 'Europe/Brussels',        phone_code: '+32',    region: 'Europe' },
  { code: 'BA', name: 'Bosnia and Herzegovina',  timezone: 'Europe/Sarajevo',        phone_code: '+387',   region: 'Europe' },
  { code: 'BG', name: 'Bulgaria',                timezone: 'Europe/Sofia',           phone_code: '+359',   region: 'Europe' },
  { code: 'HR', name: 'Croatia',                 timezone: 'Europe/Zagreb',          phone_code: '+385',   region: 'Europe' },
  { code: 'CY', name: 'Cyprus',                  timezone: 'Asia/Nicosia',           phone_code: '+357',   region: 'Europe' },
  { code: 'CZ', name: 'Czech Republic',          timezone: 'Europe/Prague',          phone_code: '+420',   region: 'Europe' },
  { code: 'DK', name: 'Denmark',                 timezone: 'Europe/Copenhagen',      phone_code: '+45',    region: 'Europe' },
  { code: 'EE', name: 'Estonia',                 timezone: 'Europe/Tallinn',         phone_code: '+372',   region: 'Europe' },
  { code: 'FI', name: 'Finland',                 timezone: 'Europe/Helsinki',        phone_code: '+358',   region: 'Europe' },
  { code: 'FR', name: 'France',                  timezone: 'Europe/Paris',           phone_code: '+33',    region: 'Europe' },
  { code: 'DE', name: 'Germany',                 timezone: 'Europe/Berlin',          phone_code: '+49',    region: 'Europe' },
  { code: 'GR', name: 'Greece',                  timezone: 'Europe/Athens',          phone_code: '+30',    region: 'Europe' },
  { code: 'HU', name: 'Hungary',                 timezone: 'Europe/Budapest',        phone_code: '+36',    region: 'Europe' },
  { code: 'IS', name: 'Iceland',                 timezone: 'Atlantic/Reykjavik',     phone_code: '+354',   region: 'Europe' },
  { code: 'IE', name: 'Ireland',                 timezone: 'Europe/Dublin',          phone_code: '+353',   region: 'Europe' },
  { code: 'IT', name: 'Italy',                   timezone: 'Europe/Rome',            phone_code: '+39',    region: 'Europe' },
  { code: 'XK', name: 'Kosovo',                  timezone: 'Europe/Belgrade',        phone_code: '+383',   region: 'Europe' },
  { code: 'LV', name: 'Latvia',                  timezone: 'Europe/Riga',            phone_code: '+371',   region: 'Europe' },
  { code: 'LI', name: 'Liechtenstein',           timezone: 'Europe/Vaduz',           phone_code: '+423',   region: 'Europe' },
  { code: 'LT', name: 'Lithuania',               timezone: 'Europe/Vilnius',         phone_code: '+370',   region: 'Europe' },
  { code: 'LU', name: 'Luxembourg',              timezone: 'Europe/Luxembourg',      phone_code: '+352',   region: 'Europe' },
  { code: 'MK', name: 'North Macedonia',         timezone: 'Europe/Skopje',          phone_code: '+389',   region: 'Europe' },
  { code: 'MT', name: 'Malta',                   timezone: 'Europe/Malta',           phone_code: '+356',   region: 'Europe' },
  { code: 'MD', name: 'Moldova',                 timezone: 'Europe/Chisinau',        phone_code: '+373',   region: 'Europe' },
  { code: 'MC', name: 'Monaco',                  timezone: 'Europe/Monaco',          phone_code: '+377',   region: 'Europe' },
  { code: 'ME', name: 'Montenegro',              timezone: 'Europe/Podgorica',       phone_code: '+382',   region: 'Europe' },
  { code: 'NL', name: 'Netherlands',             timezone: 'Europe/Amsterdam',       phone_code: '+31',    region: 'Europe' },
  { code: 'NO', name: 'Norway',                  timezone: 'Europe/Oslo',            phone_code: '+47',    region: 'Europe' },
  { code: 'PL', name: 'Poland',                  timezone: 'Europe/Warsaw',          phone_code: '+48',    region: 'Europe' },
  { code: 'PT', name: 'Portugal',                timezone: 'Europe/Lisbon',          phone_code: '+351',   region: 'Europe' },
  { code: 'RO', name: 'Romania',                 timezone: 'Europe/Bucharest',       phone_code: '+40',    region: 'Europe' },
  { code: 'RU', name: 'Russia',                  timezone: 'Europe/Moscow',          phone_code: '+7',     region: 'Europe' },
  { code: 'SM', name: 'San Marino',              timezone: 'Europe/San_Marino',      phone_code: '+378',   region: 'Europe' },
  { code: 'RS', name: 'Serbia',                  timezone: 'Europe/Belgrade',        phone_code: '+381',   region: 'Europe' },
  { code: 'SK', name: 'Slovakia',                timezone: 'Europe/Bratislava',      phone_code: '+421',   region: 'Europe' },
  { code: 'SI', name: 'Slovenia',                timezone: 'Europe/Ljubljana',       phone_code: '+386',   region: 'Europe' },
  { code: 'ES', name: 'España',                  timezone: 'Europe/Madrid',          phone_code: '+34',    region: 'Europe' },
  { code: 'SE', name: 'Sweden',                  timezone: 'Europe/Stockholm',       phone_code: '+46',    region: 'Europe' },
  { code: 'CH', name: 'Switzerland',             timezone: 'Europe/Zurich',          phone_code: '+41',    region: 'Europe' },
  { code: 'UA', name: 'Ukraine',                 timezone: 'Europe/Kiev',            phone_code: '+380',   region: 'Europe' },
  { code: 'GB', name: 'United Kingdom',          timezone: 'Europe/London',          phone_code: '+44',    region: 'Europe' },
  { code: 'VA', name: 'Vatican City',            timezone: 'Europe/Vatican',         phone_code: '+39',    region: 'Europe' },

  // ═══════════════════════════════════════════════════════════════════════
  // ASIA
  // ═══════════════════════════════════════════════════════════════════════
  { code: 'AF', name: 'Afghanistan',             timezone: 'Asia/Kabul',             phone_code: '+93',    region: 'Asia' },
  { code: 'AM', name: 'Armenia',                 timezone: 'Asia/Yerevan',           phone_code: '+374',   region: 'Asia' },
  { code: 'AZ', name: 'Azerbaijan',              timezone: 'Asia/Baku',              phone_code: '+994',   region: 'Asia' },
  { code: 'BH', name: 'Bahrain',                 timezone: 'Asia/Bahrain',           phone_code: '+973',   region: 'Asia' },
  { code: 'BD', name: 'Bangladesh',              timezone: 'Asia/Dhaka',             phone_code: '+880',   region: 'Asia' },
  { code: 'BT', name: 'Bhutan',                  timezone: 'Asia/Thimphu',           phone_code: '+975',   region: 'Asia' },
  { code: 'BN', name: 'Brunei',                  timezone: 'Asia/Brunei',            phone_code: '+673',   region: 'Asia' },
  { code: 'KH', name: 'Cambodia',                timezone: 'Asia/Phnom_Penh',        phone_code: '+855',   region: 'Asia' },
  { code: 'CN', name: 'China',                   timezone: 'Asia/Shanghai',          phone_code: '+86',    region: 'Asia' },
  { code: 'GE', name: 'Georgia',                 timezone: 'Asia/Tbilisi',           phone_code: '+995',   region: 'Asia' },
  { code: 'IN', name: 'India',                   timezone: 'Asia/Kolkata',           phone_code: '+91',    region: 'Asia' },
  { code: 'ID', name: 'Indonesia',               timezone: 'Asia/Jakarta',           phone_code: '+62',    region: 'Asia' },
  { code: 'IR', name: 'Iran',                    timezone: 'Asia/Tehran',            phone_code: '+98',    region: 'Asia' },
  { code: 'IQ', name: 'Iraq',                    timezone: 'Asia/Baghdad',           phone_code: '+964',   region: 'Asia' },
  { code: 'IL', name: 'Israel',                  timezone: 'Asia/Jerusalem',         phone_code: '+972',   region: 'Asia' },
  { code: 'JP', name: 'Japan',                   timezone: 'Asia/Tokyo',             phone_code: '+81',    region: 'Asia' },
  { code: 'JO', name: 'Jordan',                  timezone: 'Asia/Amman',             phone_code: '+962',   region: 'Asia' },
  { code: 'KZ', name: 'Kazakhstan',              timezone: 'Asia/Almaty',            phone_code: '+7',     region: 'Asia' },
  { code: 'KW', name: 'Kuwait',                  timezone: 'Asia/Kuwait',            phone_code: '+965',   region: 'Asia' },
  { code: 'KG', name: 'Kyrgyzstan',              timezone: 'Asia/Bishkek',           phone_code: '+996',   region: 'Asia' },
  { code: 'LA', name: 'Laos',                    timezone: 'Asia/Vientiane',         phone_code: '+856',   region: 'Asia' },
  { code: 'LB', name: 'Lebanon',                 timezone: 'Asia/Beirut',            phone_code: '+961',   region: 'Asia' },
  { code: 'MY', name: 'Malaysia',                timezone: 'Asia/Kuala_Lumpur',      phone_code: '+60',    region: 'Asia' },
  { code: 'MV', name: 'Maldives',                timezone: 'Indian/Maldives',        phone_code: '+960',   region: 'Asia' },
  { code: 'MN', name: 'Mongolia',                timezone: 'Asia/Ulaanbaatar',       phone_code: '+976',   region: 'Asia' },
  { code: 'MM', name: 'Myanmar',                 timezone: 'Asia/Yangon',            phone_code: '+95',    region: 'Asia' },
  { code: 'NP', name: 'Nepal',                   timezone: 'Asia/Kathmandu',         phone_code: '+977',   region: 'Asia' },
  { code: 'KP', name: 'North Korea',             timezone: 'Asia/Pyongyang',         phone_code: '+850',   region: 'Asia' },
  { code: 'OM', name: 'Oman',                    timezone: 'Asia/Muscat',            phone_code: '+968',   region: 'Asia' },
  { code: 'PK', name: 'Pakistan',                timezone: 'Asia/Karachi',           phone_code: '+92',    region: 'Asia' },
  { code: 'PS', name: 'Palestine',               timezone: 'Asia/Gaza',              phone_code: '+970',   region: 'Asia' },
  { code: 'PH', name: 'Philippines',             timezone: 'Asia/Manila',            phone_code: '+63',    region: 'Asia' },
  { code: 'QA', name: 'Qatar',                   timezone: 'Asia/Qatar',             phone_code: '+974',   region: 'Asia' },
  { code: 'SA', name: 'Saudi Arabia',            timezone: 'Asia/Riyadh',            phone_code: '+966',   region: 'Asia' },
  { code: 'SG', name: 'Singapore',               timezone: 'Asia/Singapore',         phone_code: '+65',    region: 'Asia' },
  { code: 'KR', name: 'South Korea',             timezone: 'Asia/Seoul',             phone_code: '+82',    region: 'Asia' },
  { code: 'LK', name: 'Sri Lanka',               timezone: 'Asia/Colombo',           phone_code: '+94',    region: 'Asia' },
  { code: 'SY', name: 'Syria',                   timezone: 'Asia/Damascus',          phone_code: '+963',   region: 'Asia' },
  { code: 'TW', name: 'Taiwan',                  timezone: 'Asia/Taipei',            phone_code: '+886',   region: 'Asia' },
  { code: 'TJ', name: 'Tajikistan',              timezone: 'Asia/Dushanbe',          phone_code: '+992',   region: 'Asia' },
  { code: 'TH', name: 'Thailand',                timezone: 'Asia/Bangkok',           phone_code: '+66',    region: 'Asia' },
  { code: 'TL', name: 'Timor-Leste',             timezone: 'Asia/Dili',              phone_code: '+670',   region: 'Asia' },
  { code: 'TR', name: 'Turkey',                  timezone: 'Europe/Istanbul',        phone_code: '+90',    region: 'Asia' },
  { code: 'TM', name: 'Turkmenistan',            timezone: 'Asia/Ashgabat',          phone_code: '+993',   region: 'Asia' },
  { code: 'AE', name: 'United Arab Emirates',    timezone: 'Asia/Dubai',             phone_code: '+971',   region: 'Asia' },
  { code: 'UZ', name: 'Uzbekistan',              timezone: 'Asia/Tashkent',          phone_code: '+998',   region: 'Asia' },
  { code: 'VN', name: 'Vietnam',                 timezone: 'Asia/Ho_Chi_Minh',       phone_code: '+84',    region: 'Asia' },
  { code: 'YE', name: 'Yemen',                   timezone: 'Asia/Aden',              phone_code: '+967',   region: 'Asia' },

  // ═══════════════════════════════════════════════════════════════════════
  // AFRICA
  // ═══════════════════════════════════════════════════════════════════════
  { code: 'DZ', name: 'Algeria',                 timezone: 'Africa/Algiers',         phone_code: '+213',   region: 'Africa' },
  { code: 'AO', name: 'Angola',                  timezone: 'Africa/Luanda',          phone_code: '+244',   region: 'Africa' },
  { code: 'BJ', name: 'Benin',                   timezone: 'Africa/Porto-Novo',      phone_code: '+229',   region: 'Africa' },
  { code: 'BW', name: 'Botswana',                timezone: 'Africa/Gaborone',        phone_code: '+267',   region: 'Africa' },
  { code: 'BF', name: 'Burkina Faso',            timezone: 'Africa/Ouagadougou',     phone_code: '+226',   region: 'Africa' },
  { code: 'BI', name: 'Burundi',                 timezone: 'Africa/Bujumbura',       phone_code: '+257',   region: 'Africa' },
  { code: 'CV', name: 'Cabo Verde',              timezone: 'Atlantic/Cape_Verde',    phone_code: '+238',   region: 'Africa' },
  { code: 'CM', name: 'Cameroon',                timezone: 'Africa/Douala',          phone_code: '+237',   region: 'Africa' },
  { code: 'CF', name: 'Central African Republic', timezone: 'Africa/Bangui',         phone_code: '+236',   region: 'Africa' },
  { code: 'TD', name: 'Chad',                    timezone: 'Africa/Ndjamena',        phone_code: '+235',   region: 'Africa' },
  { code: 'KM', name: 'Comoros',                 timezone: 'Indian/Comoro',          phone_code: '+269',   region: 'Africa' },
  { code: 'CG', name: 'Congo',                   timezone: 'Africa/Brazzaville',     phone_code: '+242',   region: 'Africa' },
  { code: 'CD', name: 'Congo (DRC)',             timezone: 'Africa/Kinshasa',        phone_code: '+243',   region: 'Africa' },
  { code: 'CI', name: "Côte d'Ivoire",           timezone: 'Africa/Abidjan',         phone_code: '+225',   region: 'Africa' },
  { code: 'DJ', name: 'Djibouti',                timezone: 'Africa/Djibouti',        phone_code: '+253',   region: 'Africa' },
  { code: 'EG', name: 'Egypt',                   timezone: 'Africa/Cairo',           phone_code: '+20',    region: 'Africa' },
  { code: 'GQ', name: 'Equatorial Guinea',       timezone: 'Africa/Malabo',          phone_code: '+240',   region: 'Africa' },
  { code: 'ER', name: 'Eritrea',                 timezone: 'Africa/Asmara',          phone_code: '+291',   region: 'Africa' },
  { code: 'SZ', name: 'Eswatini',                timezone: 'Africa/Mbabane',         phone_code: '+268',   region: 'Africa' },
  { code: 'ET', name: 'Ethiopia',                timezone: 'Africa/Addis_Ababa',     phone_code: '+251',   region: 'Africa' },
  { code: 'GA', name: 'Gabon',                   timezone: 'Africa/Libreville',      phone_code: '+241',   region: 'Africa' },
  { code: 'GM', name: 'Gambia',                  timezone: 'Africa/Banjul',          phone_code: '+220',   region: 'Africa' },
  { code: 'GH', name: 'Ghana',                   timezone: 'Africa/Accra',           phone_code: '+233',   region: 'Africa' },
  { code: 'GN', name: 'Guinea',                  timezone: 'Africa/Conakry',         phone_code: '+224',   region: 'Africa' },
  { code: 'GW', name: 'Guinea-Bissau',           timezone: 'Africa/Bissau',          phone_code: '+245',   region: 'Africa' },
  { code: 'KE', name: 'Kenya',                   timezone: 'Africa/Nairobi',         phone_code: '+254',   region: 'Africa' },
  { code: 'LS', name: 'Lesotho',                 timezone: 'Africa/Maseru',          phone_code: '+266',   region: 'Africa' },
  { code: 'LR', name: 'Liberia',                 timezone: 'Africa/Monrovia',        phone_code: '+231',   region: 'Africa' },
  { code: 'LY', name: 'Libya',                   timezone: 'Africa/Tripoli',         phone_code: '+218',   region: 'Africa' },
  { code: 'MG', name: 'Madagascar',              timezone: 'Indian/Antananarivo',    phone_code: '+261',   region: 'Africa' },
  { code: 'MW', name: 'Malawi',                  timezone: 'Africa/Blantyre',        phone_code: '+265',   region: 'Africa' },
  { code: 'ML', name: 'Mali',                    timezone: 'Africa/Bamako',          phone_code: '+223',   region: 'Africa' },
  { code: 'MR', name: 'Mauritania',              timezone: 'Africa/Nouakchott',      phone_code: '+222',   region: 'Africa' },
  { code: 'MU', name: 'Mauritius',               timezone: 'Indian/Mauritius',       phone_code: '+230',   region: 'Africa' },
  { code: 'MA', name: 'Morocco',                 timezone: 'Africa/Casablanca',      phone_code: '+212',   region: 'Africa' },
  { code: 'MZ', name: 'Mozambique',              timezone: 'Africa/Maputo',          phone_code: '+258',   region: 'Africa' },
  { code: 'NA', name: 'Namibia',                 timezone: 'Africa/Windhoek',        phone_code: '+264',   region: 'Africa' },
  { code: 'NE', name: 'Niger',                   timezone: 'Africa/Niamey',          phone_code: '+227',   region: 'Africa' },
  { code: 'NG', name: 'Nigeria',                 timezone: 'Africa/Lagos',           phone_code: '+234',   region: 'Africa' },
  { code: 'RW', name: 'Rwanda',                  timezone: 'Africa/Kigali',          phone_code: '+250',   region: 'Africa' },
  { code: 'ST', name: 'São Tomé and Príncipe',   timezone: 'Africa/Sao_Tome',        phone_code: '+239',   region: 'Africa' },
  { code: 'SN', name: 'Senegal',                 timezone: 'Africa/Dakar',           phone_code: '+221',   region: 'Africa' },
  { code: 'SC', name: 'Seychelles',              timezone: 'Indian/Mahe',            phone_code: '+248',   region: 'Africa' },
  { code: 'SL', name: 'Sierra Leone',            timezone: 'Africa/Freetown',        phone_code: '+232',   region: 'Africa' },
  { code: 'SO', name: 'Somalia',                 timezone: 'Africa/Mogadishu',       phone_code: '+252',   region: 'Africa' },
  { code: 'ZA', name: 'South Africa',            timezone: 'Africa/Johannesburg',    phone_code: '+27',    region: 'Africa' },
  { code: 'SS', name: 'South Sudan',             timezone: 'Africa/Juba',            phone_code: '+211',   region: 'Africa' },
  { code: 'SD', name: 'Sudan',                   timezone: 'Africa/Khartoum',        phone_code: '+249',   region: 'Africa' },
  { code: 'TZ', name: 'Tanzania',                timezone: 'Africa/Dar_es_Salaam',   phone_code: '+255',   region: 'Africa' },
  { code: 'TG', name: 'Togo',                    timezone: 'Africa/Lome',            phone_code: '+228',   region: 'Africa' },
  { code: 'TN', name: 'Tunisia',                 timezone: 'Africa/Tunis',           phone_code: '+216',   region: 'Africa' },
  { code: 'UG', name: 'Uganda',                  timezone: 'Africa/Kampala',         phone_code: '+256',   region: 'Africa' },
  { code: 'ZM', name: 'Zambia',                  timezone: 'Africa/Lusaka',          phone_code: '+260',   region: 'Africa' },
  { code: 'ZW', name: 'Zimbabwe',                timezone: 'Africa/Harare',          phone_code: '+263',   region: 'Africa' },

  // ═══════════════════════════════════════════════════════════════════════
  // OCEANIA
  // ═══════════════════════════════════════════════════════════════════════
  { code: 'AU', name: 'Australia',               timezone: 'Australia/Sydney',       phone_code: '+61',    region: 'Oceania' },
  { code: 'FJ', name: 'Fiji',                    timezone: 'Pacific/Fiji',           phone_code: '+679',   region: 'Oceania' },
  { code: 'KI', name: 'Kiribati',                timezone: 'Pacific/Tarawa',         phone_code: '+686',   region: 'Oceania' },
  { code: 'MH', name: 'Marshall Islands',        timezone: 'Pacific/Majuro',         phone_code: '+692',   region: 'Oceania' },
  { code: 'FM', name: 'Micronesia',              timezone: 'Pacific/Chuuk',          phone_code: '+691',   region: 'Oceania' },
  { code: 'NR', name: 'Nauru',                   timezone: 'Pacific/Nauru',          phone_code: '+674',   region: 'Oceania' },
  { code: 'NZ', name: 'New Zealand',             timezone: 'Pacific/Auckland',       phone_code: '+64',    region: 'Oceania' },
  { code: 'PW', name: 'Palau',                   timezone: 'Pacific/Palau',          phone_code: '+680',   region: 'Oceania' },
  { code: 'PG', name: 'Papua New Guinea',        timezone: 'Pacific/Port_Moresby',   phone_code: '+675',   region: 'Oceania' },
  { code: 'WS', name: 'Samoa',                   timezone: 'Pacific/Apia',           phone_code: '+685',   region: 'Oceania' },
  { code: 'SB', name: 'Solomon Islands',         timezone: 'Pacific/Guadalcanal',    phone_code: '+677',   region: 'Oceania' },
  { code: 'TO', name: 'Tonga',                   timezone: 'Pacific/Tongatapu',      phone_code: '+676',   region: 'Oceania' },
  { code: 'TV', name: 'Tuvalu',                  timezone: 'Pacific/Funafuti',       phone_code: '+688',   region: 'Oceania' },
  { code: 'VU', name: 'Vanuatu',                 timezone: 'Pacific/Efate',          phone_code: '+678',   region: 'Oceania' },
];
